sudo: true
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # cppcheck
  - sudo apt-get install cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download prerequisites
  - ./download_other_githubs

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Console
  - qmake TicTacToeConsole.pro
  - make debug
  #- ./TicTacToeConsole & # Do not, this causes Travis CI to play the game with the next commands
  # Desktop Qt
  - qmake TicTacToeDesktopQt.pro
  - make
  - ./TicTacToeDesktopQt &
  # Website
  - qmake TicTacToeWebsite.pro
  - make
  - ./TicTacToeWebsite &
  - sleep 10
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)