language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs


services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 TicTacToeConsoleTest.pro
  - make --silent debug
  - ./TicTacToeConsoleTest
  # Console
  - qmake -qt=qt5 TicTacToeConsole.pro
  - make --silent debug
  #- ./TicTacToeConsole & # Do not, this causes Travis CI to play the game with the next commands
  # Desktop Qt
  - qmake -qt=qt5 TicTacToeDesktopQt.pro
  - make --silent debug
  - ./TicTacToeDesktopQt &
  # Website
  - qmake -qt=qt5 TicTacToeWebsite.pro
  - make --silent debug
  - ./TicTacToeWebsite &
  - sleep 10
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . || true
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)